[workspace]
authors = ["Juliane Hoffmann <juliane.hoffmann@fau.de>", "Anne Hartebrodt <anne.hartebrodt@fau.de>"]
channels = ["conda-forge"]
name = "alternet"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
install-kernel = "python -m ipykernel install --user --name pixi_alternet --display-name pixi_alternet"

[dependencies]
python = "3.11.8.*"
pip = ">=25.1.1,<26"
ipykernel = ">=6.29.5,<7"
plotly = ">=6.1.2,<7"
requests = ">=2.0"
anndata="*"
dask="*"
dask-core="*"
dask-expr="*"
distributed="*"
networkx="*"
numba = ">=0.61.2,<0.62"
numpy="*"
pandas="*"
scanpy="*"
scikit-learn="*"
scipy="*"
seaborn="*"
tqdm="*"
umap-learn="*"
six = ">=1.17.0,<2"
scikit-learn-extra = ">=0.3.0,<0.4"
ipywidgets = ">=8.1.7,<9"
decoupler-py = ">=2.1.1,<3"
pingouin = ">=0.5.5,<0.6"

[pypi-dependencies]
rnanorm = ">=2.1.0, <3"


