# pyproject.toml
# This file defines the build system and dependencies for your Python project.

[build-system]
# This section specifies the build backend and its dependencies.
requires = ["hatchling>=1.23.0"]
build-backend = "hatchling.build"

[project]
# The core metadata for your project.
name = "alternet"
version = "0.1.0"
authors = [
  { name = "Juliane Hoffmann", email = "juliane.hoffmann@fau.de" }
]
description = "A Python package for gene regulatory network analysis."
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

# This section lists all direct dependencies for your project.
[project.dependencies]
python = ">=3.11.8,<3.12"
pip = ">=25.1.1,<26"
ipykernel = ">=6.29.5,<7"
plotly = ">=6.1.2,<7"
lda = "==3.0.0"
numpy = "==1.26.4"
scipy = "==1.12.0"
pandas = "==1.5.0"
scanpy = "==1.8.2"
matplotlib = "==3.6.3"
arboreto = "==0.1.6"
networkx = "==3.2.1"
igraph = "==0.11.8"
gseapy = "==0.10.8"

