[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "alternet"
version = "0.1.0"

authors = [
  { name="Anne Hartebrodt", email="anne.hartebrodt@fau.de" },
  {name="Juliane Hoffmann", email = "juliane.hoffmann@fau.de"}]

description = "Alternative splicing aware GRNS"
requires-python = ">=3.10"

license = { text = "GNU General Public License v3 (GPLv3)" }

urls = {Homepage = "https://github.com/bionetslab/alternet"}

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

dependencies = [
    "pip",
    "ipykernel",
    "plotly",
    "requests",
    "lda",
    "numpy",
    "scipy",
    "pandas",
    "scanpy",
    "matplotlib",
    "arboreto",
    "networkx",
    "igraph",
    "gseapy",
    "signifikante @ git+ssh://git@github.com/bionetslab/SignifiKANTE.git@main",
    "graphviz", "gprofiler-official>=1.0.0,<2",
    ]

[tool.hatch.metadata]
# This flag is required to allow direct references (like file: or git+https) 
# in the core 'project.dependencies' list.
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/alternet"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "*" 
dask = "*"
distributed = "*"
numpy = "*" 
pandas = "*"
scikit-learn = "*"
scipy = "*"
scikit-learn-extra = "*"
pyarrow = "*" 
numba = "*"
pytest = "*"
xgboost = "*"
graphviz = "*"
openpyxl = ">=3.1.5,<4"
plotly = ">=6.6.0,<7"
nbformat = ">=5.10.4,<6"

#[tool.pixi.pypi-dependencies]
#alternet = { git = "https://github.com/bionetslab/alternet.git", branch = "alternet-2.0-manual-integration" }
[tool.pixi.pypi-dependencies]
alternet = { path = ".", editable = true }

# --- DEFAULT TASKS ---
[tool.pixi.tasks]
pytest = "pytest tests/ -v"
reproduce-article-results = "python -m alternet.runners.run_pipeline_v2 --config configs/article_results_config.yaml --mode full"
reproduce-article-results-downstream = "python -m alternet.runners.run_pipeline_v2 --config configs/article_results_config.yaml --mode downstream"
construct-sf-database = "python -m alternet.runners.create_sf_database --saf data/f.1709029988.727.txt --sl data/Table_S1_datasets.xlsx --kegg data/KEGG_SPLICEOSOME.v2026.1.Hs.json --encode data/41586_2020_2077_MOESM3_ESM.xlsx -o data/splicefactors.csv"
install-kernel = "python -m ipykernel install --user --name pixi_alternet --display-name pixi_alternet"
uninstall-kernel = "jupyter kernelspec uninstall pixi_alternet"

