appris: /data_nfs/mi34qaba/SpliceAwareGRN/data/appris_data.appris.txt
biomart: ../data_nfs/biomart.txt
count_data: /data_nfs/mi34qaba/data/MAGNet/counts.csv
digger: /data_nfs/mi34qaba/SpliceAwareGRN/data/digger_data.csv
nruns: 2
parent_directory: /data_nfs/og86asub/
results_dir: /data_nfs/og86asub/alternet/results/
sample_attributes: /data_nfs/mi34qaba/data/MAGNet/phenoData.csv
tf_list: ../data_nfs/allTFs_hg38.txt
transcript_data: /data_nfs/mi34qaba/data/MAGNet/MAGNet_transcript/MAGNet_tpms.csv
tissue: NF
