name: Build and Deploy Docs

on:
  push:
    branches:
      - release

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.41.4
          cache: true

      - name: Install doc dependencies
        run: pixi run --environment docs pip install sphinx furo sphinx-autodoc-typehints nbsphinx

      - name: Build Sphinx docs
        run: pixi run --environment docs sphinx-build -b html docs/ docs/_build/html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
